/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BubbleMenu: typeof import('./src/components/TipTap/extensions/bubble-menu.vue')['default']
    CodeBlockComponent: typeof import('./src/components/TipTap/extensions/CodeBlockComponent.vue')['default']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FloatingMenu: typeof import('./src/components/TipTap/extensions/slash-menu/floating-menu.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestTemplate: typeof import('./src/components/TipTap/testTemplate.vue')['default']
    TipTap: typeof import('./src/components/TipTap/index.vue')['default']
  }
}
